import type { Tool } from "@/types/tool";
import type { Comparison } from "@/types/compare";
import type { BlogPost } from "@/types/blog";

/**
 * Mock data for development. Replace with Supabase/Sanity once connected.
 */
export const mockTools: Tool[] = [
  {
    id: "1",
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "AI assistant for conversation and tasks",
    description: "OpenAI's flagship conversational AI.",
    logo_url: null,
    website_url: "https://chat.openai.com",
    affiliate_url: null,
    category: ["writing", "productivity", "coding"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 9.2,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Versatile", "Strong reasoning", "Plugins"],
    cons: ["Rate limits on free tier"],
    best_for: ["General writing", "Research", "Coding help"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Claude",
    slug: "claude",
    tagline: "Long-form and nuanced AI",
    description: "Anthropic's AI for long-form and careful reasoning.",
    logo_url: null,
    website_url: "https://claude.ai",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 9.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Long context", "Nuanced writing", "Strong safety"],
    cons: ["Less ecosystem than ChatGPT"],
    best_for: ["Long-form content", "Analysis", "Editing"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Jasper",
    slug: "jasper",
    tagline: "AI marketing copy",
    description: "Marketing-focused AI writing and campaigns.",
    logo_url: null,
    website_url: "https://www.jasper.ai",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "paid",
    starting_price: 49,
    rating: 8.5,
    is_featured: true,
    is_sponsored: true,
    sponsored_tier: "pro",
    features: {},
    pros: ["Templates", "Brand voice", "Integrations"],
    cons: ["Higher price"],
    best_for: ["Marketing teams", "Ads", "Blogs"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Copy.ai",
    slug: "copy-ai",
    tagline: "Short-form copy at scale",
    description: "Fast short-form and ad copy generation.",
    logo_url: null,
    website_url: "https://www.copy.ai",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "freemium",
    starting_price: 0,
    rating: 8.2,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Free tier", "Fast", "Templates"],
    cons: ["Less suited to long-form"],
    best_for: ["Ads", "Social", "Product copy"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Writesonic",
    slug: "writesonic",
    tagline: "SEO and blog-focused AI",
    description: "AI writing with SEO and WordPress focus.",
    logo_url: null,
    website_url: "https://writesonic.com",
    affiliate_url: null,
    category: ["writing", "seo"],
    pricing_type: "freemium",
    starting_price: 19,
    rating: 8.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["SEO tools", "WordPress", "Chatsonic"],
    cons: ["Quality varies by template"],
    best_for: ["Bloggers", "SEO content", "Landing pages"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Grammarly",
    slug: "grammarly",
    tagline: "Writing clarity and tone",
    description: "Grammar, clarity, and AI writing assistance.",
    logo_url: null,
    website_url: "https://www.grammarly.com",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 12,
    rating: 8.8,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Everywhere you write", "Tone detection", "Plagiarism"],
    cons: ["Premium for full AI"],
    best_for: ["Emails", "Reports", "Clarity"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockComparisons: Comparison[] = [
  {
    id: "c1",
    slug: "chatgpt-vs-claude",
    tool_a_id: "1",
    tool_b_id: "2",
    title: "ChatGPT vs Claude: Which Is Better in 2026?",
    meta_desc: "Side-by-side comparison of ChatGPT and Claude. Pricing, features, and who each is best for.",
    verdict: "ChatGPT leads on ecosystem; Claude leads on long-form nuance.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[1],
  },
  {
    id: "c2",
    slug: "chatgpt-vs-jasper",
    tool_a_id: "1",
    tool_b_id: "3",
    title: "ChatGPT vs Jasper: Which Is Better for Marketing?",
    meta_desc: "Compare ChatGPT and Jasper for marketing copy, ads, and brand content.",
    verdict: "Jasper for marketing workflows; ChatGPT for versatility.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[2],
  },
  {
    id: "c3",
    slug: "best-ai-writing-tools",
    tool_a_id: "1",
    tool_b_id: "2",
    title: "Best AI Writing Tools for 2026",
    meta_desc: "Top AI writing tools compared: ChatGPT, Claude, Jasper, and more.",
    verdict: "Depends on use case: writing, marketing, or coding.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[1],
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    slug: "best-ai-writing-tools-2026",
    title: "Best AI Writing Tools for 2026",
    description: "Compare the top AI writing tools for 2026—from ChatGPT to Jasper and beyond.",
    content: "",
    date: "2026-03-07",
    readingTime: 8,
    author: "Editorial Team",
  },
  {
    slug: "chatgpt-vs-claude-2026",
    title: "ChatGPT vs Claude 2026: Which AI Is Better for You?",
    description: "ChatGPT vs Claude in 2026: we compare pricing, writing quality, coding, and speed so you can choose the right AI assistant.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "is-chatgpt-worth-it-2026",
    title: "Is ChatGPT Worth It in 2026? Honest Review",
    description: "Is ChatGPT worth paying for in 2026? We break down the free vs paid tiers, limits, and who should upgrade.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
];

export const categories = [
  { slug: "writing", name: "Writing", count: 12, icon: "✍️" },
  { slug: "image", name: "Image & Design", count: 8, icon: "🎨" },
  { slug: "productivity", name: "Productivity", count: 15, icon: "⚡" },
  { slug: "coding", name: "Coding", count: 10, icon: "💻" },
  { slug: "marketing", name: "Marketing", count: 7, icon: "📣" },
  { slug: "seo", name: "SEO", count: 5, icon: "🔍" },
];
