import type { Tool } from "@/types/tool";
import type { Comparison } from "@/types/compare";
import type { BlogPost } from "@/types/blog";

/**
 * Mock data for development. Replace with Supabase/Sanity once connected.
 */
export const mockTools: Tool[] = [
  {
    id: "1",
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "AI assistant for conversation and tasks",
    description: "OpenAI's flagship conversational AI.",
    logo_url: null,
    website_url: "https://chat.openai.com",
    affiliate_url: null,
    category: ["writing", "productivity", "coding"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 9.2,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Versatile", "Strong reasoning", "Plugins"],
    cons: ["Rate limits on free tier"],
    best_for: ["General writing", "Research", "Coding help"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "2",
    name: "Claude",
    slug: "claude",
    tagline: "Long-form and nuanced AI",
    description: "Anthropic's AI for long-form and careful reasoning.",
    logo_url: null,
    website_url: "https://claude.ai",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 9.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Long context", "Nuanced writing", "Strong safety"],
    cons: ["Less ecosystem than ChatGPT"],
    best_for: ["Long-form content", "Analysis", "Editing"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "3",
    name: "Jasper",
    slug: "jasper",
    tagline: "AI marketing copy",
    description: "Marketing-focused AI writing and campaigns.",
    logo_url: null,
    website_url: "https://www.jasper.ai",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "paid",
    starting_price: 49,
    rating: 8.5,
    is_featured: true,
    is_sponsored: true,
    sponsored_tier: "pro",
    features: {},
    pros: ["Templates", "Brand voice", "Integrations"],
    cons: ["Higher price"],
    best_for: ["Marketing teams", "Ads", "Blogs"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "4",
    name: "Copy.ai",
    slug: "copy-ai",
    tagline: "Short-form copy at scale",
    description: "Fast short-form and ad copy generation.",
    logo_url: null,
    website_url: "https://www.copy.ai",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "freemium",
    starting_price: 0,
    rating: 8.2,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Free tier", "Fast", "Templates"],
    cons: ["Less suited to long-form"],
    best_for: ["Ads", "Social", "Product copy"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "5",
    name: "Writesonic",
    slug: "writesonic",
    tagline: "SEO and blog-focused AI",
    description: "AI writing with SEO and WordPress focus.",
    logo_url: null,
    website_url: "https://writesonic.com",
    affiliate_url: null,
    category: ["writing", "seo"],
    pricing_type: "freemium",
    starting_price: 19,
    rating: 8.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["SEO tools", "WordPress", "Chatsonic"],
    cons: ["Quality varies by template"],
    best_for: ["Bloggers", "SEO content", "Landing pages"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "6",
    name: "Grammarly",
    slug: "grammarly",
    tagline: "Writing clarity and tone",
    description: "Grammar, clarity, and AI writing assistance.",
    logo_url: null,
    website_url: "https://www.grammarly.com",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 12,
    rating: 8.8,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Everywhere you write", "Tone detection", "Plagiarism"],
    cons: ["Premium for full AI"],
    best_for: ["Emails", "Reports", "Clarity"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "7",
    name: "Rytr",
    slug: "rytr",
    tagline: "AI writing on a budget",
    description: "Affordable AI writing for blogs, ads, and emails. Good for solo creators and small teams.",
    logo_url: null,
    website_url: "https://rytr.me",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "freemium",
    starting_price: 9,
    rating: 7.8,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Low cost", "Simple", "Free tier"],
    cons: ["Less brand voice control than Jasper"],
    best_for: ["Solo creators", "Budget", "Quick copy"],
    created_at: "2026-03-01T10:00:00.000Z",
    updated_at: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "8",
    name: "Midjourney",
    slug: "midjourney",
    tagline: "AI image generation, best quality",
    description: "Premium AI image generation via Discord. Industry-leading quality for art and design.",
    logo_url: null,
    website_url: "https://midjourney.com",
    affiliate_url: null,
    category: ["image"],
    pricing_type: "paid",
    starting_price: 10,
    rating: 9.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Best image quality", "Strong style control"],
    cons: ["Discord-only", "No free tier"],
    best_for: ["Artists", "Designers", "Concept art"],
    created_at: "2026-03-02T10:00:00.000Z",
    updated_at: "2026-03-02T10:00:00.000Z",
  },
  {
    id: "9",
    name: "GitHub Copilot",
    slug: "github-copilot",
    tagline: "AI pair programmer",
    description: "Code completions and suggestions inside your editor. Powered by OpenAI.",
    logo_url: null,
    website_url: "https://github.com/features/copilot",
    affiliate_url: null,
    category: ["coding", "productivity"],
    pricing_type: "freemium",
    starting_price: 10,
    rating: 8.8,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["In-editor", "Fast", "Many languages"],
    cons: ["Requires GitHub"],
    best_for: ["Developers", "Quick snippets", "Learning"],
    created_at: "2026-03-03T10:00:00.000Z",
    updated_at: "2026-03-03T10:00:00.000Z",
  },
  {
    id: "10",
    name: "Notion AI",
    slug: "notion-ai",
    tagline: "AI inside your wiki and docs",
    description: "Write, summarize, and translate inside Notion. Add-on for existing Notion users.",
    logo_url: null,
    website_url: "https://notion.so/product/ai",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "paid",
    starting_price: 10,
    rating: 8.2,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["In-context", "Summaries", "No tab switching"],
    cons: ["Extra cost on top of Notion"],
    best_for: ["Teams on Notion", "Wikis", "Knowledge bases"],
    created_at: "2026-03-04T10:00:00.000Z",
    updated_at: "2026-03-04T10:00:00.000Z",
  },
  {
    id: "11",
    name: "Perplexity",
    slug: "perplexity",
    tagline: "AI search with cited answers",
    description: "Search engine that answers with AI and cites sources. Good for research and fact-checking.",
    logo_url: null,
    website_url: "https://perplexity.ai",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 8.7,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Cited sources", "Up-to-date", "Free tier"],
    cons: ["Pro needed for some features"],
    best_for: ["Research", "Quick answers", "Citations"],
    created_at: "2026-03-05T10:00:00.000Z",
    updated_at: "2026-03-05T10:00:00.000Z",
  },
  {
    id: "12",
    name: "Canva AI",
    slug: "canva-ai",
    tagline: "AI design inside Canva",
    description: "Magic Design, text-to-image, and AI layout tools inside Canva for graphics and presentations.",
    logo_url: null,
    website_url: "https://www.canva.com",
    affiliate_url: null,
    category: ["image", "marketing"],
    pricing_type: "freemium",
    starting_price: 13,
    rating: 8.5,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Easy to use", "Templates", "Free tier"],
    cons: ["Pro for full AI suite"],
    best_for: ["Social graphics", "Presentations", "Non-designers"],
    created_at: "2026-03-05T12:00:00.000Z",
    updated_at: "2026-03-05T12:00:00.000Z",
  },
  {
    id: "13",
    name: "Gamma",
    slug: "gamma",
    tagline: "AI presentations and docs",
    description: "Create decks and documents from a prompt. AI generates structure and design.",
    logo_url: null,
    website_url: "https://gamma.app",
    affiliate_url: null,
    category: ["productivity", "marketing"],
    pricing_type: "freemium",
    starting_price: 8,
    rating: 8.3,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Fast creation", "Clean design", "Free tier"],
    cons: ["Less control than PowerPoint"],
    best_for: ["Pitches", "Docs", "Quick decks"],
    created_at: "2026-03-06T10:00:00.000Z",
    updated_at: "2026-03-06T10:00:00.000Z",
  },
  {
    id: "14",
    name: "Cursor",
    slug: "cursor",
    tagline: "AI-first code editor",
    description: "Code editor built on VS Code with native AI pair programming. Write, edit, and refactor with AI in your IDE.",
    logo_url: null,
    website_url: "https://cursor.com",
    affiliate_url: null,
    category: ["coding", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 8.9,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["VS Code compatible", "Strong AI", "Fast iteration"],
    cons: ["Paid for heavy use"],
    best_for: ["Developers", "Refactoring", "Learning"],
    created_at: "2026-03-06T14:00:00.000Z",
    updated_at: "2026-03-06T14:00:00.000Z",
  },
  {
    id: "15",
    name: "Otter.ai",
    slug: "otter-ai",
    tagline: "AI meeting notes and transcription",
    description: "Transcribe meetings, generate summaries, and sync with calendar. Real-time and post-meeting notes.",
    logo_url: null,
    website_url: "https://otter.ai",
    affiliate_url: null,
    category: ["productivity", "writing"],
    pricing_type: "freemium",
    starting_price: 10,
    rating: 8.4,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Live transcription", "Summaries", "Integrations"],
    cons: ["Free tier limits"],
    best_for: ["Meetings", "Interviews", "Lectures"],
    created_at: "2026-03-06T16:00:00.000Z",
    updated_at: "2026-03-06T16:00:00.000Z",
  },
];

export const mockComparisons: Comparison[] = [
  {
    id: "c1",
    slug: "chatgpt-vs-claude",
    tool_a_id: "1",
    tool_b_id: "2",
    title: "ChatGPT vs Claude: Which Is Better in 2026?",
    meta_desc: "Side-by-side comparison of ChatGPT and Claude. Pricing, features, and who each is best for.",
    verdict: "ChatGPT leads on ecosystem; Claude leads on long-form nuance.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[1],
  },
  {
    id: "c2",
    slug: "chatgpt-vs-jasper",
    tool_a_id: "1",
    tool_b_id: "3",
    title: "ChatGPT vs Jasper: Which Is Better for Marketing?",
    meta_desc: "Compare ChatGPT and Jasper for marketing copy, ads, and brand content.",
    verdict: "Jasper for marketing workflows; ChatGPT for versatility.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[2],
  },
  {
    id: "c3",
    slug: "best-ai-writing-tools",
    tool_a_id: "1",
    tool_b_id: "2",
    title: "Best AI Writing Tools for 2026",
    meta_desc: "Top AI writing tools compared: ChatGPT, Claude, Jasper, and more.",
    verdict: "Depends on use case: writing, marketing, or coding.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[1],
  },
  {
    id: "c4",
    slug: "claude-vs-jasper",
    tool_a_id: "2",
    tool_b_id: "3",
    title: "Claude vs Jasper: Which Is Better for Writing in 2026?",
    meta_desc: "Compare Claude and Jasper for long-form writing, marketing copy, and brand content.",
    verdict: "Claude for nuanced long-form; Jasper for marketing workflows and templates.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[1],
    tool_b: mockTools[2],
  },
  {
    id: "c5",
    slug: "chatgpt-vs-perplexity",
    tool_a_id: "1",
    tool_b_id: "11",
    title: "ChatGPT vs Perplexity 2026: Which Is Better for Research?",
    meta_desc: "Compare ChatGPT and Perplexity for research, answers, and citations. Pricing and use cases.",
    verdict: "Perplexity for cited, search-style answers; ChatGPT for open-ended chat and tasks.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[10],
  },
  {
    id: "c6",
    slug: "cursor-vs-github-copilot",
    tool_a_id: "9",
    tool_b_id: "14",
    title: "Cursor vs GitHub Copilot 2026: Which AI Code Editor?",
    meta_desc: "Compare Cursor and GitHub Copilot for AI-assisted coding. Pricing, features, and best use cases.",
    verdict: "Cursor for full IDE control and chat; Copilot for lightweight in-editor completion.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[8],
    tool_b: mockTools[13],
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    slug: "best-ai-writing-tools-2026",
    title: "Best AI Writing Tools for 2026",
    description: "Compare the top AI writing tools for 2026—from ChatGPT to Jasper and beyond.",
    content: "",
    date: "2026-03-07",
    readingTime: 8,
    author: "Editorial Team",
  },
  {
    slug: "chatgpt-vs-claude-2026",
    title: "ChatGPT vs Claude 2026: Which AI Is Better for You?",
    description: "ChatGPT vs Claude in 2026: we compare pricing, writing quality, coding, and speed so you can choose the right AI assistant.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "is-chatgpt-worth-it-2026",
    title: "Is ChatGPT Worth It in 2026? Honest Review",
    description: "Is ChatGPT worth paying for in 2026? We break down the free vs paid tiers, limits, and who should upgrade.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-free-ai-writing-tools-2026",
    title: "Best Free AI Writing Tools for 2026",
    description: "The best free AI writing tools in 2026—ChatGPT, Claude, Copy.ai, and more. Compare limits and quality.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "jasper-vs-copy-ai-2026",
    title: "Jasper vs Copy.ai 2026: Which Is Better for Marketing?",
    description: "Jasper vs Copy.ai in 2026: we compare pricing, templates, brand voice, and who each is best for—ads, blogs, or scale.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "copy-ai-review-2026",
    title: "Copy.ai Review 2026: Is It Worth It?",
    description: "Copy.ai in 2026: we review pricing, short-form quality, free tier, and who it's best for—ads, social, and emails.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "grammarly-vs-chatgpt-2026",
    title: "Grammarly vs ChatGPT 2026: Which Is Better for Writing?",
    description: "Grammarly vs ChatGPT in 2026: we compare grammar checking, style, long-form writing, and who each tool is best for.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "writesonic-review-2026",
    title: "Writesonic Review 2026: Is It Worth It for SEO and Blogs?",
    description: "Writesonic in 2026: we review pricing, SEO features, blog workflow, and who it's best for—content teams and WordPress users.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "notion-ai-review-2026",
    title: "Notion AI Review 2026: Is It Worth It for Notes and Docs?",
    description: "Notion AI in 2026: we review pricing, writing and summarization features, and who it's best for—teams and knowledge bases.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "jasper-review-2026",
    title: "Jasper Review 2026: Is It Worth It for Marketing?",
    description: "Jasper in 2026: we review pricing, brand voice, templates, and who it's best for—marketing teams and long-term brand content.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "chatgpt-plus-vs-free-2026",
    title: "ChatGPT Plus vs Free 2026: Is It Worth $20/Month?",
    description: "ChatGPT Plus vs Free in 2026: we compare limits, features, and who should pay the $20/mo—and who can stay on free.",
    content: "",
    date: "2026-03-07",
    readingTime: 3,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-image-generators-2026",
    title: "Best AI Image Generators in 2026 (Free & Paid)",
    description: "Top AI image generators in 2026: Midjourney, DALL-E, Stable Diffusion, and more. Compare quality, price, and best use cases.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-coding-tools-2026",
    title: "Best AI Coding Tools for Developers in 2026",
    description: "Top AI coding tools in 2026: GitHub Copilot, Cursor, Tabnine, and more. Compare features, price, and best use cases for developers.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-free-ai-tools-no-credit-card-2026",
    title: "Best Free AI Tools in 2026 (No Credit Card Needed)",
    description: "Free AI tools you can use in 2026 without a credit card: ChatGPT, Claude, Copy.ai, and more. Compare limits and quality.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-tools-for-students-2026",
    title: "Best AI Tools for Students in 2026",
    description: "Top AI tools for students in 2026: writing, research, math, and study aids. Free and affordable options compared.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "how-to-choose-ai-tool-2026",
    title: "How to Choose the Right AI Tool in 2026",
    description: "A simple framework to pick the right AI tool: use case, budget, and must-have features. Compare writing, research, coding, and design tools.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-tools-small-business-2026",
    title: "Best AI Tools for Small Business in 2026",
    description: "AI tools that help small businesses: marketing, writing, support, and productivity. Compare free and paid options.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
];

export const categories = [
  { slug: "writing", name: "Writing", count: 12, icon: "✍️" },
  { slug: "image", name: "Image & Design", count: 8, icon: "🎨" },
  { slug: "productivity", name: "Productivity", count: 15, icon: "⚡" },
  { slug: "coding", name: "Coding", count: 10, icon: "💻" },
  { slug: "marketing", name: "Marketing", count: 7, icon: "📣" },
  { slug: "seo", name: "SEO", count: 5, icon: "🔍" },
];
