import type { Tool } from "@/types/tool";
import type { Comparison } from "@/types/compare";
import type { BlogPost } from "@/types/blog";

/**
 * Mock data for development. Replace with Supabase/Sanity once connected.
 */
export const mockTools: Tool[] = [
  {
    id: "1",
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "AI assistant for conversation and tasks",
    description: "OpenAI's flagship conversational AI.",
    logo_url: null,
    website_url: "https://chat.openai.com",
    affiliate_url: null,
    category: ["writing", "productivity", "coding"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 9.2,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Versatile", "Strong reasoning", "Plugins"],
    cons: ["Rate limits on free tier"],
    best_for: ["General writing", "Research", "Coding help"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "2",
    name: "Claude",
    slug: "claude",
    tagline: "Long-form and nuanced AI",
    description: "Anthropic's AI for long-form and careful reasoning.",
    logo_url: null,
    website_url: "https://claude.ai",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 9.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Long context", "Nuanced writing", "Strong safety"],
    cons: ["Less ecosystem than ChatGPT"],
    best_for: ["Long-form content", "Analysis", "Editing"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "3",
    name: "Jasper",
    slug: "jasper",
    tagline: "AI marketing copy",
    description: "Marketing-focused AI writing and campaigns.",
    logo_url: null,
    website_url: "https://www.jasper.ai",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "paid",
    starting_price: 49,
    rating: 8.5,
    is_featured: true,
    is_sponsored: true,
    sponsored_tier: "pro",
    features: {},
    pros: ["Templates", "Brand voice", "Integrations"],
    cons: ["Higher price"],
    best_for: ["Marketing teams", "Ads", "Blogs"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "4",
    name: "Copy.ai",
    slug: "copy-ai",
    tagline: "Short-form copy at scale",
    description: "Fast short-form and ad copy generation.",
    logo_url: null,
    website_url: "https://www.copy.ai",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "freemium",
    starting_price: 0,
    rating: 8.2,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Free tier", "Fast", "Templates"],
    cons: ["Less suited to long-form"],
    best_for: ["Ads", "Social", "Product copy"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "5",
    name: "Writesonic",
    slug: "writesonic",
    tagline: "SEO and blog-focused AI",
    description: "AI writing with SEO and WordPress focus.",
    logo_url: null,
    website_url: "https://writesonic.com",
    affiliate_url: null,
    category: ["writing", "seo"],
    pricing_type: "freemium",
    starting_price: 19,
    rating: 8.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["SEO tools", "WordPress", "Chatsonic"],
    cons: ["Quality varies by template"],
    best_for: ["Bloggers", "SEO content", "Landing pages"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "6",
    name: "Grammarly",
    slug: "grammarly",
    tagline: "Writing clarity and tone",
    description: "Grammar, clarity, and AI writing assistance.",
    logo_url: null,
    website_url: "https://www.grammarly.com",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 12,
    rating: 8.8,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Everywhere you write", "Tone detection", "Plagiarism"],
    cons: ["Premium for full AI"],
    best_for: ["Emails", "Reports", "Clarity"],
    created_at: "2026-02-15T12:00:00.000Z",
    updated_at: "2026-02-15T12:00:00.000Z",
  },
  {
    id: "7",
    name: "Rytr",
    slug: "rytr",
    tagline: "AI writing on a budget",
    description: "Affordable AI writing for blogs, ads, and emails. Good for solo creators and small teams.",
    logo_url: null,
    website_url: "https://rytr.me",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "freemium",
    starting_price: 9,
    rating: 7.8,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Low cost", "Simple", "Free tier"],
    cons: ["Less brand voice control than Jasper"],
    best_for: ["Solo creators", "Budget", "Quick copy"],
    created_at: "2026-03-01T10:00:00.000Z",
    updated_at: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "8",
    name: "Midjourney",
    slug: "midjourney",
    tagline: "The gold standard for AI image generation",
    description: "Midjourney produces stunning, artistic AI-generated images via Discord. Known for its exceptional image quality and unique aesthetic style.",
    logo_url: null,
    website_url: "https://midjourney.com",
    affiliate_url: null,
    category: ["image", "productivity"],
    pricing_type: "paid",
    starting_price: 10,
    rating: 9.4,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Best image quality available", "Unique artistic style", "Active community", "Regular updates"],
    cons: ["Discord-only interface", "No free tier", "Learning curve for prompts", "No API access on basic plan"],
    best_for: ["Designers", "Artists", "Marketing creatives", "Content creators"],
    created_at: "2026-03-02T10:00:00.000Z",
    updated_at: "2026-03-02T10:00:00.000Z",
  },
  {
    id: "9",
    name: "GitHub Copilot",
    slug: "github-copilot",
    tagline: "AI pair programmer",
    description: "Code completions and suggestions inside your editor. Powered by OpenAI.",
    logo_url: null,
    website_url: "https://github.com/features/copilot",
    affiliate_url: null,
    category: ["coding", "productivity"],
    pricing_type: "freemium",
    starting_price: 10,
    rating: 8.8,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["In-editor", "Fast", "Many languages"],
    cons: ["Requires GitHub"],
    best_for: ["Developers", "Quick snippets", "Learning"],
    created_at: "2026-03-03T10:00:00.000Z",
    updated_at: "2026-03-03T10:00:00.000Z",
  },
  {
    id: "10",
    name: "Notion AI",
    slug: "notion-ai",
    tagline: "AI inside your wiki and docs",
    description: "Write, summarize, and translate inside Notion. Add-on for existing Notion users.",
    logo_url: null,
    website_url: "https://notion.so/product/ai",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "paid",
    starting_price: 10,
    rating: 8.2,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["In-context", "Summaries", "No tab switching"],
    cons: ["Extra cost on top of Notion"],
    best_for: ["Teams on Notion", "Wikis", "Knowledge bases"],
    created_at: "2026-03-04T10:00:00.000Z",
    updated_at: "2026-03-04T10:00:00.000Z",
  },
  {
    id: "11",
    name: "Perplexity",
    slug: "perplexity",
    tagline: "AI search with cited answers",
    description: "Search engine that answers with AI and cites sources. Good for research and fact-checking.",
    logo_url: null,
    website_url: "https://perplexity.ai",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 8.7,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Cited sources", "Up-to-date", "Free tier"],
    cons: ["Pro needed for some features"],
    best_for: ["Research", "Quick answers", "Citations"],
    created_at: "2026-03-05T10:00:00.000Z",
    updated_at: "2026-03-05T10:00:00.000Z",
  },
  {
    id: "12",
    name: "Canva AI",
    slug: "canva-ai",
    tagline: "AI design inside Canva",
    description: "Magic Design, text-to-image, and AI layout tools inside Canva for graphics and presentations.",
    logo_url: null,
    website_url: "https://www.canva.com",
    affiliate_url: null,
    category: ["image", "marketing"],
    pricing_type: "freemium",
    starting_price: 13,
    rating: 8.5,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Easy to use", "Templates", "Free tier"],
    cons: ["Pro for full AI suite"],
    best_for: ["Social graphics", "Presentations", "Non-designers"],
    created_at: "2026-03-05T12:00:00.000Z",
    updated_at: "2026-03-05T12:00:00.000Z",
  },
  {
    id: "13",
    name: "Gamma",
    slug: "gamma",
    tagline: "AI presentations and docs",
    description: "Create decks and documents from a prompt. AI generates structure and design.",
    logo_url: null,
    website_url: "https://gamma.app",
    affiliate_url: null,
    category: ["productivity", "marketing"],
    pricing_type: "freemium",
    starting_price: 8,
    rating: 8.3,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Fast creation", "Clean design", "Free tier"],
    cons: ["Less control than PowerPoint"],
    best_for: ["Pitches", "Docs", "Quick decks"],
    created_at: "2026-03-06T10:00:00.000Z",
    updated_at: "2026-03-06T10:00:00.000Z",
  },
  {
    id: "14",
    name: "Cursor",
    slug: "cursor",
    tagline: "AI-first code editor",
    description: "Code editor built on VS Code with native AI pair programming. Write, edit, and refactor with AI in your IDE.",
    logo_url: null,
    website_url: "https://cursor.com",
    affiliate_url: null,
    category: ["coding", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 8.9,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["VS Code compatible", "Strong AI", "Fast iteration"],
    cons: ["Paid for heavy use"],
    best_for: ["Developers", "Refactoring", "Learning"],
    created_at: "2026-03-06T14:00:00.000Z",
    updated_at: "2026-03-06T14:00:00.000Z",
  },
  {
    id: "15",
    name: "Otter.ai",
    slug: "otter-ai",
    tagline: "AI meeting notes and transcription",
    description: "Transcribe meetings, generate summaries, and sync with calendar. Real-time and post-meeting notes.",
    logo_url: null,
    website_url: "https://otter.ai",
    affiliate_url: null,
    category: ["productivity", "writing"],
    pricing_type: "freemium",
    starting_price: 10,
    rating: 8.4,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Live transcription", "Summaries", "Integrations"],
    cons: ["Free tier limits"],
    best_for: ["Meetings", "Interviews", "Lectures"],
    created_at: "2026-03-06T16:00:00.000Z",
    updated_at: "2026-03-06T16:00:00.000Z",
  },
  {
    id: "16",
    name: "Canva",
    slug: "canva",
    tagline: "AI-powered design for everyone",
    description: "Create graphics, presentations, and videos with AI templates and Magic Design. Simple drag-and-drop for non-designers.",
    logo_url: null,
    website_url: "https://www.canva.com",
    affiliate_url: null,
    category: ["image", "productivity", "marketing"],
    pricing_type: "freemium",
    starting_price: 13,
    rating: 8.7,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Easy to use", "Templates", "AI design tools"],
    cons: ["Pro for best assets"],
    best_for: ["Social graphics", "Presentations", "Quick design"],
    created_at: "2026-03-07T12:00:00.000Z",
    updated_at: "2026-03-07T12:00:00.000Z",
  },
  {
    id: "17",
    name: "Descript",
    slug: "descript",
    tagline: "Edit video and audio by editing text",
    description: "Record, transcribe, and edit video and podcasts. Edit by cutting or rewriting the transcript; AI fills in the rest.",
    logo_url: null,
    website_url: "https://www.descript.com",
    affiliate_url: null,
    category: ["productivity", "writing"],
    pricing_type: "freemium",
    starting_price: 12,
    rating: 8.6,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Transcript-based editing", "Overdub", "Podcast workflow"],
    cons: ["Learning curve for full features"],
    best_for: ["Podcasters", "YouTubers", "Video creators"],
    created_at: "2026-03-07T12:00:00.000Z",
    updated_at: "2026-03-07T12:00:00.000Z",
  },
  {
    id: "18",
    name: "Loom",
    slug: "loom",
    tagline: "Async video messages and AI summaries",
    description: "Record quick video updates and screen shares. AI generates captions and summaries so teammates can skim or watch.",
    logo_url: null,
    website_url: "https://www.loom.com",
    affiliate_url: null,
    category: ["productivity"],
    pricing_type: "freemium",
    starting_price: 8,
    rating: 8.5,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Fast recording", "AI captions", "Async communication"],
    cons: ["Storage limits on free"],
    best_for: ["Remote teams", "Support", "Product demos"],
    created_at: "2026-03-07T12:00:00.000Z",
    updated_at: "2026-03-07T12:00:00.000Z",
  },
  {
    id: "19",
    name: "Anyword",
    slug: "anyword",
    tagline: "AI writing with performance prediction",
    description: "Anyword uses predictive analytics to score your copy before you publish, helping marketers write content that actually converts.",
    logo_url: null,
    website_url: "https://anyword.com",
    affiliate_url: null,
    category: ["writing", "marketing"],
    pricing_type: "paid",
    starting_price: 49,
    rating: 8.1,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Unique performance prediction score", "Great for ad copy", "Custom brand voice", "Team features"],
    cons: ["More expensive than competitors", "Learning curve", "Best for marketers not general writers"],
    best_for: ["Performance marketers", "Ad copywriters", "Marketing teams", "eCommerce brands"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
  },
  {
    id: "20",
    name: "Wordtune",
    slug: "wordtune",
    tagline: "Rewrite and improve any sentence instantly",
    description: "Wordtune is an AI-powered writing companion that helps you rewrite, rephrase, and improve your existing text for clarity and tone.",
    logo_url: null,
    website_url: "https://wordtune.com",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 14.99,
    rating: 8.0,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Excellent rewriting quality", "Great Chrome extension", "Free tier available", "Intuitive UI"],
    cons: ["Not great for long-form generation", "Limited use cases vs competitors", "Free tier very limited"],
    best_for: ["Students", "Non-native English speakers", "Professionals improving emails", "Content editors"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
  },
  {
    id: "21",
    name: "Adobe Firefly",
    slug: "adobe-firefly",
    tagline: "Commercially safe AI image generation",
    description: "Adobe Firefly is trained on licensed images, making it safe for commercial use. Integrated directly into Adobe Creative Cloud apps.",
    logo_url: null,
    website_url: "https://firefly.adobe.com",
    affiliate_url: null,
    category: ["image", "productivity"],
    pricing_type: "freemium",
    starting_price: 4.99,
    rating: 8.6,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["100% commercially safe", "Photoshop integration", "Great text effects", "Generous free credits"],
    cons: ["Less artistic than Midjourney", "Requires Adobe account", "Credits expire monthly"],
    best_for: ["Graphic designers", "Marketing professionals", "Adobe Creative Cloud users", "Commercial projects"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
  },
  {
    id: "22",
    name: "Ideogram",
    slug: "ideogram",
    tagline: "AI image generation with perfect text rendering",
    description: "Ideogram excels at generating images with accurate, readable text — something most AI image tools struggle with significantly.",
    logo_url: null,
    website_url: "https://ideogram.ai",
    affiliate_url: null,
    category: ["image", "productivity"],
    pricing_type: "freemium",
    starting_price: 8,
    rating: 8.3,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Best text-in-image rendering", "Great for logos and posters", "Generous free tier", "Fast generation"],
    cons: ["Less photorealistic than competitors", "Smaller community", "Limited advanced controls"],
    best_for: ["Logo designers", "Poster creators", "Social media graphics", "Typography projects"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
  },
  {
    id: "23",
    name: "Tabnine",
    slug: "tabnine",
    tagline: "Private, secure AI code completion",
    description: "Tabnine offers AI code completion with a strong focus on privacy. Your code never leaves your machine on the local model option.",
    logo_url: null,
    website_url: "https://www.tabnine.com",
    affiliate_url: null,
    category: ["coding", "productivity"],
    pricing_type: "freemium",
    starting_price: 12,
    rating: 8.2,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Privacy-first approach", "Local model option", "Works offline", "Good team features"],
    cons: ["Less capable than Copilot/Cursor", "Local model is slower", "UI feels dated"],
    best_for: ["Privacy-conscious developers", "Enterprise teams", "Regulated industries", "Offline development"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
  },
  {
    id: "24",
    name: "Gemini",
    slug: "gemini",
    tagline: "Google's AI assistant",
    description: "Google's Gemini (formerly Bard) is a conversational AI with deep integration into Google Search, Workspace, and ecosystem.",
    logo_url: null,
    website_url: "https://gemini.google.com",
    affiliate_url: null,
    category: ["writing", "productivity"],
    pricing_type: "freemium",
    starting_price: 20,
    rating: 8.8,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Google ecosystem integration", "Free tier", "Multimodal", "Up-to-date search"],
    cons: ["Tied to Google account", "Some features region-locked"],
    best_for: ["Google Workspace users", "Research", "General writing", "Quick answers"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
  },
  // VPN niche (NordVPN & NordPass)
  {
    id: "vpn1",
    name: "NordVPN",
    slug: "nordvpn",
    tagline: "Fast, secure VPN with thousands of servers",
    description:
      "NordVPN is a premium VPN service with thousands of servers worldwide, strong encryption, and fast speeds for streaming and browsing.",
    logo_url: null,
    website_url: "https://nordvpn.com",
    affiliate_url: null,
    category: ["vpn", "security"],
    pricing_type: "paid",
    starting_price: 3.99,
    rating: 9.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Fast speeds", "Large server network", "Strong encryption", "Streaming-friendly"],
    cons: ["Best pricing on long-term plans", "App UI can feel busy"],
    best_for: ["Streaming", "Privacy", "Travelers"],
    created_at: "2026-03-08T10:00:00.000Z",
    updated_at: "2026-03-08T10:00:00.000Z",
    niche: "vpn",
  },
  {
    id: "vpn2",
    name: "NordPass",
    slug: "nordpass",
    tagline: "Password manager by the Nord Security team",
    description:
      "NordPass is a secure password manager from the creators of NordVPN. Store and autofill passwords across devices with zero-knowledge encryption.",
    logo_url: null,
    website_url: "https://nordpass.com",
    affiliate_url: null,
    category: ["security", "productivity"],
    pricing_type: "paid",
    starting_price: 1.49,
    rating: 8.4,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Zero-knowledge encryption", "Easy to use", "Good autofill", "Family plans"],
    cons: ["Smaller ecosystem than some competitors", "Best value on multi-year plans"],
    best_for: ["Individuals", "Families", "Remote workers"],
    created_at: "2026-03-08T10:00:00.000Z",
    updated_at: "2026-03-08T10:00:00.000Z",
    niche: "vpn",
  },
  // Web Hosting niche (Hostinger — use affiliate from lib/affiliate.ts)
  {
    id: "wh1",
    name: "Hostinger",
    slug: "hostinger",
    tagline: "Best value web hosting for beginners",
    description: "Hostinger offers fast, affordable web hosting starting at just $2.99/month. Great for beginners with an easy setup and 99.9% uptime guarantee.",
    logo_url: null,
    website_url: "https://www.hostinger.com",
    affiliate_url: null,
    category: ["shared", "wordpress", "vps"],
    pricing_type: "paid",
    starting_price: 2.99,
    rating: 9.1,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Cheapest quality hosting available", "Fast loading speeds", "Free domain included", "24/7 live chat support", "Easy hPanel control panel"],
    cons: ["Renewal prices higher than intro", "No monthly billing on cheapest plan", "Phone support not available"],
    best_for: ["Beginners", "Bloggers", "Small businesses", "WordPress sites", "Budget-conscious buyers"],
    created_at: "2026-03-07T10:00:00.000Z",
    updated_at: "2026-03-07T10:00:00.000Z",
    niche: "web-hosting",
  },
  {
    id: "wh2",
    name: "Bluehost",
    slug: "bluehost",
    tagline: "WordPress-recommended hosting",
    description: "One of the most recommended hosts for WordPress. Shared, VPS, and dedicated options with easy setup.",
    logo_url: null,
    website_url: "https://www.bluehost.com",
    affiliate_url: null,
    category: ["shared", "wordpress"],
    pricing_type: "paid",
    starting_price: 3,
    rating: 8.5,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["WordPress optimized", "Free domain year one", "cPanel"],
    cons: ["Renewal prices higher"],
    best_for: ["WordPress", "Blogs", "Small business"],
    created_at: "2026-03-07T10:00:00.000Z",
    updated_at: "2026-03-07T10:00:00.000Z",
    niche: "web-hosting",
  },
  {
    id: "wh3",
    name: "SiteGround",
    slug: "siteground",
    tagline: "Premium support and performance",
    description: "Managed hosting with strong security, staging, and support. Good for agencies and growing sites.",
    logo_url: null,
    website_url: "https://www.siteground.com",
    affiliate_url: null,
    category: ["shared", "wordpress", "cloud"],
    pricing_type: "paid",
    starting_price: 4,
    rating: 9.0,
    is_featured: true,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Great support", "Staging", "Security tools"],
    cons: ["Higher price"],
    best_for: ["Agencies", "WooCommerce", "Growing sites"],
    created_at: "2026-03-07T10:00:00.000Z",
    updated_at: "2026-03-07T10:00:00.000Z",
    niche: "web-hosting",
  },
  {
    id: "wh4",
    name: "A2 Hosting",
    slug: "a2-hosting",
    tagline: "Fast, developer-friendly hosting",
    description: "Turbo servers and optional root access. Good for developers and speed-focused sites.",
    logo_url: null,
    website_url: "https://www.a2hosting.com",
    affiliate_url: null,
    category: ["shared", "vps", "wordpress"],
    pricing_type: "paid",
    starting_price: 3,
    rating: 8.6,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Turbo option", "Developer tools", "Anycast DNS"],
    cons: ["Interface feels dated"],
    best_for: ["Developers", "Fast sites", "WooCommerce"],
    created_at: "2026-03-07T10:00:00.000Z",
    updated_at: "2026-03-07T10:00:00.000Z",
    niche: "web-hosting",
  },
  {
    id: "wh5",
    name: "WP Engine",
    slug: "wp-engine",
    tagline: "Premium managed WordPress hosting",
    description: "WP Engine is the leading managed WordPress hosting platform, used by over 1.5 million sites worldwide. Premium performance, security, and support.",
    logo_url: null,
    website_url: "https://www.wpengine.com",
    affiliate_url: null,
    category: ["wordpress", "shared"],
    pricing_type: "paid",
    starting_price: 30,
    rating: 9.2,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Best managed WordPress hosting", "Exceptional speed & performance", "Automatic backups", "Staging environments", "Expert WordPress support"],
    cons: ["Expensive starting at $30/mo", "WordPress only", "Bandwidth limits", "No email hosting"],
    best_for: ["Serious WordPress sites", "eCommerce stores", "Agencies", "High traffic websites"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
    niche: "web-hosting",
  },
  {
    id: "wh6",
    name: "Cloudways",
    slug: "cloudways",
    tagline: "Managed cloud hosting made simple",
    description: "Cloudways lets you deploy on top cloud providers (AWS, Google Cloud, DigitalOcean) with a simple management interface. No server management required.",
    logo_url: null,
    website_url: "https://www.cloudways.com",
    affiliate_url: null,
    category: ["shared", "vps"],
    pricing_type: "paid",
    starting_price: 14,
    rating: 8.9,
    is_featured: false,
    is_sponsored: false,
    sponsored_tier: null,
    features: {},
    pros: ["Choose your cloud provider", "Excellent performance", "Pay-as-you-go pricing", "Free SSL and CDN", "Great for developers"],
    cons: ["No email hosting", "Learning curve vs shared hosting", "Support can be slow on basic plan"],
    best_for: ["Developers", "Growing websites", "Agencies", "WooCommerce stores", "Performance-focused sites"],
    created_at: "2026-03-07T14:00:00.000Z",
    updated_at: "2026-03-07T14:00:00.000Z",
    niche: "web-hosting",
  },
];

export const mockComparisons: Comparison[] = [
  {
    id: "c1",
    slug: "chatgpt-vs-claude",
    tool_a_id: "1",
    tool_b_id: "2",
    title: "ChatGPT vs Claude: Which Is Better in 2026?",
    meta_desc: "Side-by-side comparison of ChatGPT and Claude. Pricing, features, and who each is best for.",
    verdict: "ChatGPT leads on ecosystem; Claude leads on long-form nuance.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[1],
  },
  {
    id: "c2",
    slug: "chatgpt-vs-jasper",
    tool_a_id: "1",
    tool_b_id: "3",
    title: "ChatGPT vs Jasper: Which Is Better for Marketing?",
    meta_desc: "Compare ChatGPT and Jasper for marketing copy, ads, and brand content.",
    verdict: "Jasper for marketing workflows; ChatGPT for versatility.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[2],
  },
  {
    id: "c3",
    slug: "best-ai-writing-tools",
    tool_a_id: "1",
    tool_b_id: "2",
    title: "Best AI Writing Tools for 2026",
    meta_desc: "Top AI writing tools compared: ChatGPT, Claude, Jasper, and more.",
    verdict: "Depends on use case: writing, marketing, or coding.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[1],
  },
  {
    id: "c4",
    slug: "claude-vs-jasper",
    tool_a_id: "2",
    tool_b_id: "3",
    title: "Claude vs Jasper: Which Is Better for Writing in 2026?",
    meta_desc: "Compare Claude and Jasper for long-form writing, marketing copy, and brand content.",
    verdict: "Claude for nuanced long-form; Jasper for marketing workflows and templates.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[1],
    tool_b: mockTools[2],
  },
  {
    id: "c5",
    slug: "chatgpt-vs-perplexity",
    tool_a_id: "1",
    tool_b_id: "11",
    title: "ChatGPT vs Perplexity 2026: Which Is Better for Research?",
    meta_desc: "Compare ChatGPT and Perplexity for research, answers, and citations. Pricing and use cases.",
    verdict: "Perplexity for cited, search-style answers; ChatGPT for open-ended chat and tasks.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[0],
    tool_b: mockTools[10],
  },
  {
    id: "c6",
    slug: "cursor-vs-github-copilot",
    tool_a_id: "9",
    tool_b_id: "14",
    title: "Cursor vs GitHub Copilot 2026: Which AI Code Editor?",
    meta_desc: "Compare Cursor and GitHub Copilot for AI-assisted coding. Pricing, features, and best use cases.",
    verdict: "Cursor for full IDE control and chat; Copilot for lightweight in-editor completion.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[8],
    tool_b: mockTools[13],
  },
  {
    id: "c7",
    slug: "claude-vs-perplexity",
    tool_a_id: "2",
    tool_b_id: "11",
    title: "Claude vs Perplexity 2026: Which for Research and Writing?",
    meta_desc: "Compare Claude and Perplexity for research, long-form writing, and cited answers. Pricing and use cases.",
    verdict: "Perplexity for search-style answers and citations; Claude for long-form writing and analysis.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[1],
    tool_b: mockTools[10],
  },
  {
    id: "c8",
    slug: "hostinger-vs-bluehost",
    tool_a_id: "wh1",
    tool_b_id: "wh2",
    title: "Hostinger vs Bluehost 2026: Which Web Host Is Better?",
    meta_desc: "Compare Hostinger and Bluehost for price, performance, and WordPress. Best for beginners and small sites.",
    verdict: "Hostinger for lowest price and solid value; Bluehost for WordPress-first workflows and official recommendation.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[24],
    tool_b: mockTools[25],
    niche: "web-hosting",
  },
  {
    id: "c9",
    slug: "siteground-vs-a2-hosting",
    tool_a_id: "wh3",
    tool_b_id: "wh4",
    title: "SiteGround vs A2 Hosting 2026: Which Is Better?",
    meta_desc: "Compare SiteGround and A2 Hosting for support, speed, and value. Best for agencies vs developers.",
    verdict: "SiteGround for premium support and staging; A2 for Turbo speed and developer-friendly options.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[26],
    tool_b: mockTools[27],
    niche: "web-hosting",
  },
  {
    id: "c10",
    slug: "hostinger-vs-siteground",
    tool_a_id: "wh1",
    tool_b_id: "wh3",
    title: "Hostinger vs SiteGround 2026: Budget vs Premium Hosting",
    meta_desc: "Compare Hostinger and SiteGround: price, performance, and support. Best for starters vs growing sites.",
    verdict: "Hostinger for lowest cost and good value; SiteGround for best support and managed features.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[24],
    tool_b: mockTools[26],
    niche: "web-hosting",
  },
  {
    id: "c11",
    slug: "jasper-vs-copy-ai",
    tool_a_id: "3",
    tool_b_id: "4",
    title: "Jasper vs Copy.ai 2026: Which Is Better for Marketing?",
    meta_desc: "Compare Jasper and Copy.ai for marketing copy, ads, and brand voice. Pricing and use cases.",
    verdict: "Jasper for full brand voice and workflows; Copy.ai for speed and value on short-form.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[2],
    tool_b: mockTools[3],
  },
  {
    id: "c12",
    slug: "claude-vs-gemini",
    tool_a_id: "2",
    tool_b_id: "24",
    title: "Claude vs Gemini 2026: Which AI Is Better?",
    meta_desc: "Compare Claude and Gemini on writing, coding, reasoning, and pricing. Who should use which in 2026?",
    verdict: "Claude for long-form writing and nuance; Gemini for Google ecosystem and free tier.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[1],
    tool_b: mockTools[23],
  },
  {
    id: "c13",
    slug: "midjourney-vs-adobe-firefly",
    tool_a_id: "8",
    tool_b_id: "21",
    title: "Midjourney vs Adobe Firefly 2026: Which AI Image Tool Wins?",
    meta_desc: "Compare Midjourney and Adobe Firefly on image quality, commercial use, and ease of use.",
    verdict: "Midjourney for best image quality; Firefly for commercial safety and Adobe integration.",
    content: null,
    views: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    tool_a: mockTools[7],
    tool_b: mockTools[20],
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    slug: "best-ai-writing-tools-2026",
    title: "Best AI Writing Tools for 2026",
    description: "Compare the top AI writing tools for 2026—from ChatGPT to Jasper and beyond.",
    content: "",
    date: "2026-03-07",
    readingTime: 8,
    author: "Editorial Team",
  },
  {
    slug: "chatgpt-vs-claude-2026",
    title: "ChatGPT vs Claude 2026: Which AI Is Better for You?",
    description: "ChatGPT vs Claude in 2026: we compare pricing, writing quality, coding, and speed so you can choose the right AI assistant.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "is-chatgpt-worth-it-2026",
    title: "Is ChatGPT Worth It in 2026? Honest Review",
    description: "Is ChatGPT worth paying for in 2026? We break down the free vs paid tiers, limits, and who should upgrade.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-free-ai-writing-tools-2026",
    title: "Best Free AI Writing Tools for 2026",
    description: "The best free AI writing tools in 2026—ChatGPT, Claude, Copy.ai, and more. Compare limits and quality.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "jasper-vs-copy-ai-2026",
    title: "Jasper vs Copy.ai 2026: Which Is Better for Marketing?",
    description: "Jasper vs Copy.ai in 2026: we compare pricing, templates, brand voice, and who each is best for—ads, blogs, or scale.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "copy-ai-review-2026",
    title: "Copy.ai Review 2026: Is It Worth It?",
    description: "Copy.ai in 2026: we review pricing, short-form quality, free tier, and who it's best for—ads, social, and emails.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "grammarly-vs-chatgpt-2026",
    title: "Grammarly vs ChatGPT 2026: Which Is Better for Writing?",
    description: "Grammarly vs ChatGPT in 2026: we compare grammar checking, style, long-form writing, and who each tool is best for.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "writesonic-review-2026",
    title: "Writesonic Review 2026: Is It Worth It for SEO and Blogs?",
    description: "Writesonic in 2026: we review pricing, SEO features, blog workflow, and who it's best for—content teams and WordPress users.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "notion-ai-review-2026",
    title: "Notion AI Review 2026: Is It Worth It for Notes and Docs?",
    description: "Notion AI in 2026: we review pricing, writing and summarization features, and who it's best for—teams and knowledge bases.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "jasper-review-2026",
    title: "Jasper Review 2026: Is It Worth It for Marketing?",
    description: "Jasper in 2026: we review pricing, brand voice, templates, and who it's best for—marketing teams and long-term brand content.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "chatgpt-plus-vs-free-2026",
    title: "ChatGPT Plus vs Free 2026: Is It Worth $20/Month?",
    description: "ChatGPT Plus vs Free in 2026: we compare limits, features, and who should pay the $20/mo—and who can stay on free.",
    content: "",
    date: "2026-03-07",
    readingTime: 3,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-image-generators-2026",
    title: "Best AI Image Generators in 2026 (Free & Paid)",
    description: "Top AI image generators in 2026: Midjourney, DALL-E, Stable Diffusion, and more. Compare quality, price, and best use cases.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-coding-tools-2026",
    title: "Best AI Coding Tools for Developers in 2026",
    description: "Top AI coding tools in 2026: GitHub Copilot, Cursor, Tabnine, and more. Compare features, price, and best use cases for developers.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-free-ai-tools-no-credit-card-2026",
    title: "Best Free AI Tools in 2026 (No Credit Card Needed)",
    description: "Free AI tools you can use in 2026 without a credit card: ChatGPT, Claude, Copy.ai, and more. Compare limits and quality.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-tools-for-students-2026",
    title: "Best AI Tools for Students in 2026",
    description: "Top AI tools for students in 2026: writing, research, math, and study aids. Free and affordable options compared.",
    content: "",
    date: "2026-03-07",
    readingTime: 4,
    author: "Editorial Team",
  },
  {
    slug: "how-to-choose-ai-tool-2026",
    title: "How to Choose the Right AI Tool in 2026",
    description: "A simple framework to pick the right AI tool: use case, budget, and must-have features. Compare writing, research, coding, and design tools.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-tools-small-business-2026",
    title: "Best AI Tools for Small Business in 2026",
    description: "AI tools that help small businesses: marketing, writing, support, and productivity. Compare free and paid options.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-tools-content-creators-2026",
    title: "Best AI Tools for Content Creators in 2026",
    description: "AI tools for YouTubers, bloggers, and creators: scripts, thumbnails, captions, and SEO. Free and paid picks.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "best-web-hosting-wordpress-2026",
    title: "Best Web Hosting for WordPress in 2026",
    description: "Top WordPress hosting compared: Hostinger, Bluehost, SiteGround, and A2. Price, performance, and who each is best for.",
    content: "",
    date: "2026-03-07",
    readingTime: 6,
    author: "Editorial Team",
  },
  {
    slug: "canva-vs-descript-2026",
    title: "Canva vs Descript 2026: Which Tool for Creators?",
    description: "Canva for design and social; Descript for video and podcasts. We compare pricing and best use cases for creators.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-tools-remote-teams-2026",
    title: "Best AI Tools for Remote Teams in 2026",
    description: "AI tools that help remote teams: async video (Loom), meeting notes (Otter), writing (Claude), and more.",
    content: "",
    date: "2026-03-07",
    readingTime: 5,
    author: "Editorial Team",
  },
  {
    slug: "best-ai-tools-freelancers-2026",
    title: "Best AI Tools for Freelancers in 2026",
    description: "Freelancers are using AI to work 3x faster. Here are the best AI tools for writers, designers, developers, and marketers in 2026.",
    content: "",
    date: "2026-03-07",
    readingTime: 6,
    author: "Editorial Team",
  },
  {
    slug: "chatgpt-vs-claude-vs-gemini-2026",
    title: "ChatGPT vs Claude vs Gemini: The Ultimate Comparison 2026",
    description: "ChatGPT, Claude, or Gemini — which AI assistant is best in 2026? We compare all three on writing, coding, reasoning, pricing, and more.",
    content: "",
    date: "2026-03-07",
    readingTime: 8,
    author: "Editorial Team",
  },
  {
    slug: "best-web-hosting-beginners-2026",
    title: "Best Web Hosting for Beginners in 2026 (Cheap & Reliable)",
    description: "New to web hosting? We compared 10+ providers to find the best hosting for beginners in 2026 — fast, affordable, and easy to set up.",
    content: "",
    date: "2026-03-07",
    readingTime: 6,
    author: "Editorial Team",
  },
  {
    slug: "hostinger-review-2026",
    title: "Hostinger Review 2026: Is It Really Worth $2.99/Month?",
    description: "Is Hostinger actually worth it? We tested Hostinger's speed, uptime, support, and features. Here's our honest verdict for 2026.",
    content: "",
    date: "2026-03-07",
    readingTime: 6,
    author: "Editorial Team",
  },
];

export const categories = [
  { slug: "writing", name: "Writing", count: 12, icon: "✍️" },
  { slug: "image", name: "Image & Design", count: 8, icon: "🎨" },
  { slug: "productivity", name: "Productivity", count: 15, icon: "⚡" },
  { slug: "coding", name: "Coding", count: 10, icon: "💻" },
  { slug: "marketing", name: "Marketing", count: 7, icon: "📣" },
  { slug: "seo", name: "SEO", count: 5, icon: "🔍" },
];
